# Generated by Django 3.0.7 on 2023-01-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
